#!/usr/bin/env python3
"""Generate Prover.toml with proper test inputs for honeypot verifier."""

def generate_identity_matrices(count: int) -> list[str]:
    """Generate `count` identity matrices as flat array of field elements."""
    identity = [
        "1", "0", "0", "0", "0",
        "0", "1", "0", "0", "0",
        "0", "0", "1", "0", "0",
        "0", "0", "0", "1", "0",
        "0", "0", "0", "0", "1"
    ]
    result = []
    for _ in range(count):
        result.extend(identity)
    return result

def main():
    # Generate 128 identity matrices = 3200 elements
    matrices = generate_identity_matrices(128)
    assert len(matrices) == 3200, f"Expected 3200, got {len(matrices)}"
    
    # Compute simple hash matching Noir circuit
    # simple_hash samples every 32nd element
    hash_val = 0
    for i in range(100):
        idx = i * 32
        if idx < len(matrices):
            hash_val += int(matrices[idx]) * (i + 1)
    
    toml_content = f'''# Test inputs for honeypot verifier
# Generated by generate_prover_toml.py

# Public inputs
obf_prog_hash = "{hash_val}"
evaluation_output = "1"

# Private witness: 12 BIP-39 word indices (0-2047)
seed_phrase = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]

# Matrix branching program (3200 field elements = 128 steps x 25 entries)
bp_matrices_flat = [
'''
    
    # Add matrices in rows of 25 (one matrix per line for readability)
    for i in range(128):
        start = i * 25
        end = start + 25
        row = matrices[start:end]
        toml_content += '    ' + ', '.join(f'"{x}"' for x in row)
        if i < 127:
            toml_content += ','
        toml_content += '\n'
    
    toml_content += ']\n'
    
    with open('Prover.toml', 'w') as f:
        f.write(toml_content)
    
    print(f"Generated Prover.toml with {len(matrices)} matrix elements")
    print(f"Hash value: {hash_val}")

if __name__ == "__main__":
    main()
